apiVersion: v2
name: game-app-ingress
description: A Helm chart for any full game application (Deployment, Service and Ingress)
type: application
version: 0.1.0
appVersion: 1.16.0
home: https://github.com/git4suvendu/game-app/tree/master/helm
sources:
  - https://github.com/git4suvendu/game-app/tree/master/helm
maintainers:
  - name: Suvendu Mandal
    url: https://github.com/git4suvendu
    email: m_andal2002@yahoo.co.in
keywords:
  - app
  - gameapp-ingress