# Default values for game-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


environment:
  releaseName: sample-env-release

namespace:
  enabled: false
  name:

nameOverride:
fullnameOverride:

replicaCount: 3

deployment:
  name:

image:
  repository: public.ecr.aws/nginx/nginx   #public.ecr.aws/l6m2t8p7/docker-2048 
  pullPolicy: Always
  tag: "1.21"  # "latest"
  containerName:
  containerPort: 80


service:
  name:
  type: NodePort
  port: 80
  targetPort: 80
  protocol: TCP



ingress:
  name:
  enabled: true
  userAnnotations: 
    org.landg/group: "LGRS"
  defaultAnnotations:
    ingressType:
      ingressClass: "alb"
      ingressScheme: internal  #internet-facing   
      ingressTargetType: ip
    healthCheck:
      healthCheckProtocol: "HTTP" 
      healthCheckPath: "/"
      healthCheckIntervalSeconds: "15"
      healthCheckTimeoutSeconds: "5"
      heathCheckSuccessCodes: "200"
      healthyThresholdCount: "2"
      unhealthyThresholdCount: "2"
  paths:
    - path: /
      pathType: Prefix
      svcName: "sample-service1"  
      svcPort: 80

