# Default values for game-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


environment:
  releaseName: sample-env-release

namespace:
  enabled: false
  name: ""

nameOverride: ""
fullnameOverride: ""

replicaCount: 3

deployment:
  name: ""

image:
  repository: public.ecr.aws/l6m2t8p7/docker-2048    #public.ecr.aws/nginx/nginx:1.21
  pullPolicy: Always
  tag: "latest"
  containerPort: 80


service:
  name: ""
  type: NodePort
  port: 80
  targetPort: 80
  protocol: TCP



ingress:
  name: ""
  enabled: true
  className: "alb"
  userAnnotations: 
    landg/ingress.group: "lgrs"
  defaultAnnotations:
    ingressType:
      ingressClass: "alb"
      ingressScheme: internal
      ingressTargetType: ip
    healthCheck:
      healthCheckProtocol: "HTTP" 
      healthCheckPath: "/example-service/hello"
      healthCheckIntervalSeconds: "15"
      healthCheckTimeoutSeconds: "5"
      heathCheckSuccessCodes: "200"
      healthyThresholdCount: "2"
      unhealthyThresholdCount: "2"
  paths:
    - path: /foo/
      pathType: Prefix
      svcName: "sample-service1"
      svcPort: 80
    - path: /bar/
      pathType: Prefix
      svcName: "sample-service2"
      svcPort: 80
    - path: /
      pathType: Prefix
      svcName: "sample-service3"
      svcPort: 80

