apiVersion: v2
name: generic-application-landg-updated
description: A Helm chart for generic-application (Deployment, Service and Ingress)
type: application
version: 0.2.0
appVersion: 1.16.0
home: https://github.com/git4suvendu/application-helm-charts
sources:
  - https://github.com/git4suvendu/application-helm-charts
maintainers:
  - name: Suvendu Mandal
    url: https://github.com/git4suvendu
    email: suvendu.mandal@landg.com
keywords:
  - app
  - generic-application-landg-updated
  - generic-application-template
  
